name: Deploy DynamoDB CRUD API

on:
  push:
    branches: [ main ]

jobs: 
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with: 
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
      
    - name: Install dependencies
      run: yarn install

    - name: Install Serverless Framework
      run: npm install -g serverless
    
    - name: Serverless AWS authentication
      run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

    - name: serverless deploy
      run: serverless deploy